#!/bin/bash

RED='\033[0;31m'
NC='\033[0m'
lkm_e="encriptador"
lkm_d="desencriptador"

echo -e "Removiendo Modulos"
sudo rmmod ${lkm_e}
echo -e "Modulo ${RED}${lkm_e}${NC} removido"
sudo rmmod ${lkm_d}
echo -e "Modulo ${RED}${lkm_d}${NC} removido"
echo ""
echo -e "Eliminando entrada de /dev para ${lkm_e}"
sudo rm /dev/${lkm_e}
echo "/dev/${lkm_e} -> Eliminada"
echo ""
echo "Eliminando entrada de /dev para ${lkm_d}"
sudo rm /dev/${lkm_d} 
echo "/dev/${lkm_d} -> Eliminada"
